### ISSUE TITLE
Not working on x86 powershell

### ISSUE THREAD

**Issue by legoritma** [Windos/BurntToast#5] opened 2016-08-25 06:47 UTC
Windows 10 x64 - x86 powershell
```
PS C:\WINDOWS\system32> New-BurntToastNotification
Get-StartApps : The term 'Get-StartApps' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files (x86)\WindowsPowerShell\Modules\BurntToast\0.4\New-BurntToastNotification.ps1:117 char:31
+         [String] $AppId = ( ((Get-StartApps -Name '*PowerShell*') | S ...
+                               ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-StartApps:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

```

**Comment by Windos** [comment] 2016-08-27 06:01
Hey @legoritma, thanks for opening this ticket. I'm working on a fix (or more accuratly re-writting specifically for Windows 10.) I'll provide updates on this via Issue #4, feel free to follow that for updates!

**Comment by Windos** [comment] 2016-08-27 06:02
Duplicate of issue #251

**Closed by Windos** 2016-08-27 06:02 UTC
